function settings = reconstruction_defaults(cam)
% RECONSTRUCTION_DEFAULTS Settings for stages AFTER the warm motion fit.
% cam.focal and cam.principal are [1,2] ideal-pinhole pixel parameters.
% These defaults reproduce the constants in main_reconstruction_gold.m.
% Set start/end/warm duration and dt to match YOUR front end before running.
settings.start_time_s = 60;
settings.end_time_s = 185;
settings.warm_duration_s = 6;
settings.slice_s = 0.1;
settings.adjustment = struct('focal', reshape(double(cam.focal),1,2), ...
    'principal', reshape(double(cam.principal),1,2), ...
    'sigma',0.5, 'eps',0.15, 'cauchy',4, 'lam_th',500, 'lam_T',200, ...
    'pull',0.1, 'gauge',1e4, 'centroid',1e2, 'min_depth',0.2, ...
    'damping0',1e-3, 'free_V',false, 'fd_check',false);
settings.association = struct('gate_n',3, 'gate_t',8, 'cov_gate',0.03, ...
    'local_win',3, 'min_mature',6, 'knot_iters',3, 'cand_gate',3, ...
    'cand_max_miss',5, 'cand_min_samples',12, 'cand_min_turn',deg2rad(8), ...
    'cand_min_depth',0.3, 'cand_max_rms',2, 'seed_cell',6, 'min_events',3, ...
    'dt',settings.slice_s, 'focal',settings.adjustment.focal, ...
    'principal',settings.adjustment.principal, 'eps',settings.adjustment.eps, ...
    'image_size',[640 480], 'free_V',settings.adjustment.free_V);
settings.schedule = struct('warm_iterations',20, 'local_every',10, ...
    'local_iterations',8, 'global_every',100, 'global_iterations',10, ...
    'early_global_batches',[10 30 60], 'knots_free_after_s',0, ...
    'min_nobs_global',10, 'final_iterations',[20 10], ...
    'final_min_obs',20, 'final_max_rms_px',2, 'print_every',100);
settings.output = struct('root',fullfile(pwd,'output_simplified'), ...
    'known_width_m',1.27, 'scale_endpoint_ids',[], ...
    'make_figures',true, 'save_checkpoints',true);
end
